name: chatx
description: Chat Application using socket nodejs & flutter.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  socket_io_client: ^2.0.2
  go_router: ^9.0.0
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  google_fonts: ^5.1.0
  response_x: ^1.0.2
  random_avatar: ^0.0.8
  intl: ^0.18.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
